# Python Data Analysis | 👋🏼 ⭐️⭐️⭐️⭐️⭐️ 👾
Treehouse Live with Jonathan Barrios: Python Data Analysis with Jupyter Notebook, Pandas, Numpy, Matplotlib, and Seaborn from the very beginning 🌐 Watch the [archived Livestream](https://join.teamtreehouse.com/treehouse-live/) 🍿


# 🐍 PART I | 5.22.2020

## Import data analysis libraries pandas and numpy

In [21]:
# import pandas as pd
import pandas as pd
# import numpy as np
import numpy as np

### Create some test data
##### Let's use [numpy.random.randint](https://numpy.org/doc/1.18/reference/random/generated/numpy.random.randint.html?highlight=randint#numpy.random.randint) for this

In [22]:
# Use numpy to generate 25 random integers between 1-100
test_data = np.random.randint(1,100,100)

### Return that data

In [23]:
# Return data
test_data

array([26, 41, 38, 93, 61, 41, 96, 56, 32, 69, 27, 79, 36, 69, 48, 68, 87,
       40,  2, 97, 54, 20, 70, 18, 47, 71, 48, 92, 16, 81, 28,  9, 16,  6,
       83, 27, 57, 69, 52,  3, 33, 66, 60, 44, 94, 66, 34, 55, 31, 85,  5,
        8, 18, 79,  6,  6, 90, 96, 90, 29, 90, 65, 19, 26, 40, 20, 92,  3,
       50, 91, 43, 71, 96, 20, 16, 32, 60, 26,  7, 48, 86, 48, 92, 53, 64,
       98, 83, 90,  7, 63, 29, 10, 33, 12, 65, 75,  8, 86, 16, 71])

## Create star ratings test data ⭐️⭐️⭐️⭐️⭐️
##### Let's use [numpy.linspace](https://numpy.org/devdocs/reference/generated/numpy.linspace.html) for this

In [24]:
# Create random floats wich are evenly spaced between 1 and 5
data = np.linspace(1,5,25)

### Return that data

In [25]:
# Return data
data

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        , 2.16666667, 2.33333333, 2.5       ,
       2.66666667, 2.83333333, 3.        , 3.16666667, 3.33333333,
       3.5       , 3.66666667, 3.83333333, 4.        , 4.16666667,
       4.33333333, 4.5       , 4.66666667, 4.83333333, 5.        ])

### Wrangle that data

In [26]:
# Round the number with one decimal integer
data = np.around(np.linspace(1,5,25),1)

### Return that data

In [27]:
# Return data
data

array([1. , 1.2, 1.3, 1.5, 1.7, 1.8, 2. , 2.2, 2.3, 2.5, 2.7, 2.8, 3. ,
       3.2, 3.3, 3.5, 3.7, 3.8, 4. , 4.2, 4.3, 4.5, 4.7, 4.8, 5. ])

# What is Pandas?
Pandas is data analysis tool built on top of Python.

# What is a Pandas Series?
A Pandas Series is a one-dimensional labeled array that holds any data type (integer, string, float, python objects, etc.). In short, a Pandas Series is nothing but a **column** in an excel sheet. Let's make one!

In [28]:
# Make Pandas Series
series = pd.Series(data)

### Return Pandas  Series

In [29]:
# Return Sesries
series

0     1.0
1     1.2
2     1.3
3     1.5
4     1.7
5     1.8
6     2.0
7     2.2
8     2.3
9     2.5
10    2.7
11    2.8
12    3.0
13    3.2
14    3.3
15    3.5
16    3.7
17    3.8
18    4.0
19    4.2
20    4.3
21    4.5
22    4.7
23    4.8
24    5.0
dtype: float64

### Return an index that starts at 1 instead of 0

In [30]:
# Set index to 1
series.index = series.index + 1 
# return series
series

1     1.0
2     1.2
3     1.3
4     1.5
5     1.7
6     1.8
7     2.0
8     2.2
9     2.3
10    2.5
11    2.7
12    2.8
13    3.0
14    3.2
15    3.3
16    3.5
17    3.7
18    3.8
19    4.0
20    4.2
21    4.3
22    4.5
23    4.7
24    4.8
25    5.0
dtype: float64

### Series mean

In [31]:
# Return series.mean()
series.mean()

3.0

### Series by Index

In [32]:
# return series[by_index]
series[13]

3.0

### Series are one dimensional

In [33]:
# Return series.shape
series.shape

(25,)

# What is a DataFrame?
The long answer is a two-dimensional size-mutable, potentially heterogeneous tabular data structure with labeled axes. The short answer is, **rows and columns**.

### Pandas Data Frames are two dimensional(rows & columns)

In [34]:
# Create a two dimensional data frame
df = pd.DataFrame(data, columns=['ratings'])

### Return two dimensional data frame

In [35]:
# Return two dimensional data frame
df

ratings
0       1.0
1       1.2
2       1.3
3       1.5
4       1.7
5       1.8
6       2.0
7       2.2
8       2.3
9       2.5
10      2.7
11      2.8
12      3.0
13      3.2
14      3.3
15      3.5
16      3.7
17      3.8
18      4.0
19      4.2
20      4.3
21      4.5
22      4.7
23      4.8
24      5.0

### Set index to start at index 1

In [36]:
# Set index to 1
df.index = df.index + 1

### Return the two dimensional data frame starting at index 1

In [37]:
df

ratings
1       1.0
2       1.2
3       1.3
4       1.5
5       1.7
6       1.8
7       2.0
8       2.2
9       2.3
10      2.5
11      2.7
12      2.8
13      3.0
14      3.2
15      3.3
16      3.5
17      3.7
18      3.8
19      4.0
20      4.2
21      4.3
22      4.5
23      4.7
24      4.8
25      5.0

# 🐍 PART II | 5.29.2020

### Check the type for a DataFrame?

In [38]:
# return type()


### Extract DataFrame rows using [iloc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html) with indices 2,3, and 8.

- [iloc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html) -- Selecting data by row numbers (.iloc)

- [loc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html) -- Selecting data by label or by a conditional statment (.loc)

In [39]:
# extract data using iloc indices 2,3 and 8


### Return new data frame 

In [ ]:
# return new data frame


### Extract DataFrame rows using the index syntax :6

In [41]:
# return new data frame using the index :6 syntax


### Return new data frame displaying result using :6 

In [42]:
# return new data frame displaying result using :6 




# Review: Series vs DataFrames
Series have one column while data frames have rows and columns. Let's compare them below:

In [43]:
# check type() for mini_data_frame

In [ ]:
# check type() for mini_series = df.iloc[2]

## Mean, median, describe and more...
- [mean()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.mean.html)
- [median()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.median.html?highlight=dataframe%20median#pandas.DataFrame.median)
- [describe()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.describe.html?highlight=dataframe%20describe#pandas.DataFrame.describe)
- [max()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.max.html#pandas.DataFrame.max)
- [min()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.max.html#pandas.DataFrame.min)

In [ ]:
# return mean()

In [ ]:
# return median()

In [ ]:
# return describe()

# Remember this test data we generated with Numpy?

In [45]:
# earlier test data

test_data = np.random.randint(1,80, 25)

# return that data

test_data

array([58,  1, 34, 50, 20, 33, 23, 64, 69, 64, 63, 77, 23, 31, 67, 13, 48,
       73, 10, 74, 42, 58, 75, 17, 16])

### How about multidemensional array?

In [49]:
# reshape() test data with a 5 x 5 multidimensional array

test_data = np.random.randint(1,80, 25).reshape(5,5)

# return that data

test_data

array([[78, 17, 59,  5, 48],
       [39, 73, 17,  2, 23],
       [34, 61, 38, 55, 31],
       [75, 77,  7, 64, 50],
       [15,  5, 31,  6,  5]])

### What's the shape() of this array?

In [50]:
# return shape() of test_data
test_data.shape

(5, 5)

### Convert the test_data into a test_data_frame

In [51]:
# return test_data_frame


### add descriptive column names

In [52]:
# add descriptive column names


In [53]:
# return test_data_frame as df


### add descriptive index names

In [54]:
# add descriptive index names


In [55]:
# return test_data_frame as df


### What's the 411? or info()?

In [ ]:
# return info()


### Perform math operations on columns saved as 'Total'

In [ ]:
# add the sum of each rows to a new column, 'Total'


### Return new DataFrame

In [ ]:
# return new data frame


### Perform boolean operations on columns saved as 'Profit'

In [59]:
# check each row for boolean condition of > 200 to a new column, 'Profit'


### Return new DataFrame

In [ ]:
# return new data frame


### Drop the 'Profit' column
Use the optinal parameters: axis=0 for index, and axis=1 for columns (default =0)

Read more on [DataFrame.drop()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html?highlight=dataframe%20drop#pandas.DataFrame.drop)

In [57]:
# drop the 'Profit' column (using the correct axis=*)


### Return new DataFrame without the 'Profit' column

In [ ]:
# return new data frame


# Matplotlib and Seaborn

### Import pyplot from matplotlib as plt
### Import seaborn as sns

In [56]:
# import pyplot from matplotlib as plt

# import seaborn as sns


### Create a plot using pyplot as plt

In [60]:
# Create a plot with pyplot as plt using new_df and the 'Total' column
