# Python Data Analysis | 👋🏼 ⭐️⭐️⭐️⭐️⭐️ 👾
Treehouse Live with Jonathan Barrios: Python Data Analysis with Jupyter Notebook, Pandas, Numpy, Matplotlib, and Seaborn from the very beginning 🌐 Watch the [archived Livestream](https://join.teamtreehouse.com/treehouse-live/) 🍿


# PART I | 5.22.2020

## Import data analysis libraries pandas and numpy

In [1]:
# import pandas as pd
import pandas as pd
# import numpy as np
import numpy as np

### Create some test data
##### Let's use [numpy.random.randint](https://numpy.org/doc/1.18/reference/random/generated/numpy.random.randint.html?highlight=randint#numpy.random.randint) for this

In [5]:
# Use numpy to generate 25 random integers between 1-100
test_data = np.random.randint(1,100,100)

### Return that data

In [6]:
# Return data
test_data

array([21, 61, 19, 88, 64, 69, 74,  5, 91, 97, 87, 72, 53,  4, 17, 16, 29,
       27, 77, 21, 81, 74, 45, 12, 90,  8, 12,  5, 26, 27, 47, 69, 18, 37,
       73, 14, 53, 10, 88,  5, 44, 44, 49, 46, 33, 81, 29,  5, 67, 11, 49,
       36, 96, 19, 17, 53, 58, 46, 56, 72, 35, 68, 47, 45, 86,  2, 19, 87,
       63, 71, 54, 83, 89,  1, 67, 95, 58, 55,  3,  9, 62, 26, 43, 53, 67,
       27, 37, 82, 96, 47, 87, 37, 38, 69, 14, 66, 23, 92, 12, 82])

## Create star ratings test data ⭐️⭐️⭐️⭐️⭐️
##### Let's use [numpy.linspace](https://numpy.org/devdocs/reference/generated/numpy.linspace.html) for this

In [8]:
# Create random floats wich are evenly spaced between 1 and 5
data = np.linspace(1,5,25)

### Return that data

In [9]:
# Return data
data

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        , 2.16666667, 2.33333333, 2.5       ,
       2.66666667, 2.83333333, 3.        , 3.16666667, 3.33333333,
       3.5       , 3.66666667, 3.83333333, 4.        , 4.16666667,
       4.33333333, 4.5       , 4.66666667, 4.83333333, 5.        ])

### Wrangle that data

In [12]:
# Round the number with one decimal integer
data = np.around(np.linspace(1,5,25),1)

### Return that data

In [13]:
# Return data
data

array([1. , 1.2, 1.3, 1.5, 1.7, 1.8, 2. , 2.2, 2.3, 2.5, 2.7, 2.8, 3. ,
       3.2, 3.3, 3.5, 3.7, 3.8, 4. , 4.2, 4.3, 4.5, 4.7, 4.8, 5. ])

# What is Pandas?
Pandas is data analysis tool built on top of Python.

# What is a Pandas Series?
A Pandas Series is a one-dimensional labeled array that holds any data type (integer, string, float, python objects, etc.). In short, a Pandas Series is nothing but a **column** in an excel sheet. Let's make one!

In [14]:
# Make Pandas Series
series = pd.Series(data)

### Return Pandas  Series

In [15]:
# Return Sesries
series

0     1.0
1     1.2
2     1.3
3     1.5
4     1.7
5     1.8
6     2.0
7     2.2
8     2.3
9     2.5
10    2.7
11    2.8
12    3.0
13    3.2
14    3.3
15    3.5
16    3.7
17    3.8
18    4.0
19    4.2
20    4.3
21    4.5
22    4.7
23    4.8
24    5.0
dtype: float64

### Return an index that starts at 1 instead of 0

In [16]:
# Set index to 1
series.index = series.index + 1 
# return series
series

1     1.0
2     1.2
3     1.3
4     1.5
5     1.7
6     1.8
7     2.0
8     2.2
9     2.3
10    2.5
11    2.7
12    2.8
13    3.0
14    3.2
15    3.3
16    3.5
17    3.7
18    3.8
19    4.0
20    4.2
21    4.3
22    4.5
23    4.7
24    4.8
25    5.0
dtype: float64

### Series mean

In [18]:
# Return series.mean()
series.mean()

3.0

### Series by Index

In [20]:
# return series[by_index]
series[13]

3.0

### Series are one dimensional

In [21]:
# Return series.shape
series.shape

(25,)

# What is a DataFrame?
The long answer is a two-dimensional size-mutable, potentially heterogeneous tabular data structure with labeled axes. The short answer is, **rows and columns**.

### Pandas Data Frames are two dimensional(rows & columns)

In [22]:
# Create a two dimensional data frame
df = pd.DataFrame(data, columns=['ratings'])

### Return two dimensional data frame

In [24]:
# Return two dimensional data frame
df

ratings
0       1.0
1       1.2
2       1.3
3       1.5
4       1.7
5       1.8
6       2.0
7       2.2
8       2.3
9       2.5
10      2.7
11      2.8
12      3.0
13      3.2
14      3.3
15      3.5
16      3.7
17      3.8
18      4.0
19      4.2
20      4.3
21      4.5
22      4.7
23      4.8
24      5.0

### Return the two dimensional data frame starting at index 1

In [28]:
# Set index to 1
df.index = df.index - 2

df

ratings
1       1.0
2       1.2
3       1.3
4       1.5
5       1.7
6       1.8
7       2.0
8       2.2
9       2.3
10      2.5
11      2.7
12      2.8
13      3.0
14      3.2
15      3.3
16      3.5
17      3.7
18      3.8
19      4.0
20      4.2
21      4.3
22      4.5
23      4.7
24      4.8
25      5.0

# PART II

Part II next Friday 1pm PST here: [https://join.teamtreehouse.com/treehouse-live/](https://join.teamtreehouse.com/treehouse-live/)